// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksservice

import (
	context "context"

	domain "github.com/stazoloto/zync/internal/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/stazoloto/zync/internal/service"
)

// MockAdminService is an autogenerated mock type for the AdminService type
type MockAdminService struct {
	mock.Mock
}

type MockAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminService) EXPECT() *MockAdminService_Expecter {
	return &MockAdminService_Expecter{mock: &_m.Mock}
}

// CloseRoom provides a mock function with given fields: ctx, roomID
func (_m *MockAdminService) CloseRoom(ctx context.Context, roomID string) error {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for CloseRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminService_CloseRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseRoom'
type MockAdminService_CloseRoom_Call struct {
	*mock.Call
}

// CloseRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockAdminService_Expecter) CloseRoom(ctx interface{}, roomID interface{}) *MockAdminService_CloseRoom_Call {
	return &MockAdminService_CloseRoom_Call{Call: _e.mock.On("CloseRoom", ctx, roomID)}
}

func (_c *MockAdminService_CloseRoom_Call) Run(run func(ctx context.Context, roomID string)) *MockAdminService_CloseRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdminService_CloseRoom_Call) Return(_a0 error) *MockAdminService_CloseRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminService_CloseRoom_Call) RunAndReturn(run func(context.Context, string) error) *MockAdminService_CloseRoom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: userID
func (_m *MockAdminService) DeleteUser(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockAdminService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - userID string
func (_e *MockAdminService_Expecter) DeleteUser(userID interface{}) *MockAdminService_DeleteUser_Call {
	return &MockAdminService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", userID)}
}

func (_c *MockAdminService_DeleteUser_Call) Run(run func(userID string)) *MockAdminService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAdminService_DeleteUser_Call) Return(_a0 error) *MockAdminService_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminService_DeleteUser_Call) RunAndReturn(run func(string) error) *MockAdminService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveRooms provides a mock function with given fields: ctx
func (_m *MockAdminService) ListActiveRooms(ctx context.Context) ([]service.RoomInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveRooms")
	}

	var r0 []service.RoomInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]service.RoomInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []service.RoomInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.RoomInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminService_ListActiveRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveRooms'
type MockAdminService_ListActiveRooms_Call struct {
	*mock.Call
}

// ListActiveRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminService_Expecter) ListActiveRooms(ctx interface{}) *MockAdminService_ListActiveRooms_Call {
	return &MockAdminService_ListActiveRooms_Call{Call: _e.mock.On("ListActiveRooms", ctx)}
}

func (_c *MockAdminService_ListActiveRooms_Call) Run(run func(ctx context.Context)) *MockAdminService_ListActiveRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminService_ListActiveRooms_Call) Return(_a0 []service.RoomInfo, _a1 error) *MockAdminService_ListActiveRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminService_ListActiveRooms_Call) RunAndReturn(run func(context.Context) ([]service.RoomInfo, error)) *MockAdminService_ListActiveRooms_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with no fields
func (_m *MockAdminService) ListUsers() ([]*domain.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*domain.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*domain.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockAdminService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
func (_e *MockAdminService_Expecter) ListUsers() *MockAdminService_ListUsers_Call {
	return &MockAdminService_ListUsers_Call{Call: _e.mock.On("ListUsers")}
}

func (_c *MockAdminService_ListUsers_Call) Run(run func()) *MockAdminService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdminService_ListUsers_Call) Return(_a0 []*domain.User, _a1 error) *MockAdminService_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminService_ListUsers_Call) RunAndReturn(run func() ([]*domain.User, error)) *MockAdminService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SetRole provides a mock function with given fields: userID, role
func (_m *MockAdminService) SetRole(userID string, role string) error {
	ret := _m.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for SetRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminService_SetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRole'
type MockAdminService_SetRole_Call struct {
	*mock.Call
}

// SetRole is a helper method to define mock.On call
//   - userID string
//   - role string
func (_e *MockAdminService_Expecter) SetRole(userID interface{}, role interface{}) *MockAdminService_SetRole_Call {
	return &MockAdminService_SetRole_Call{Call: _e.mock.On("SetRole", userID, role)}
}

func (_c *MockAdminService_SetRole_Call) Run(run func(userID string, role string)) *MockAdminService_SetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAdminService_SetRole_Call) Return(_a0 error) *MockAdminService_SetRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminService_SetRole_Call) RunAndReturn(run func(string, string) error) *MockAdminService_SetRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminService creates a new instance of MockAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminService {
	mock := &MockAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
