// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksservice

import (
	context "context"

	domain "github.com/stazoloto/zync/internal/domain"
	mock "github.com/stretchr/testify/mock"

	webrtc "github.com/pion/webrtc/v3"
)

// MockSignalingService is an autogenerated mock type for the SignalingService type
type MockSignalingService struct {
	mock.Mock
}

type MockSignalingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSignalingService) EXPECT() *MockSignalingService_Expecter {
	return &MockSignalingService_Expecter{mock: &_m.Mock}
}

// HandleAnswer provides a mock function with given fields: ctx, roomID, peerID, answer
func (_m *MockSignalingService) HandleAnswer(ctx context.Context, roomID string, peerID string, answer webrtc.SessionDescription) error {
	ret := _m.Called(ctx, roomID, peerID, answer)

	if len(ret) == 0 {
		panic("no return value specified for HandleAnswer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, webrtc.SessionDescription) error); ok {
		r0 = rf(ctx, roomID, peerID, answer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSignalingService_HandleAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAnswer'
type MockSignalingService_HandleAnswer_Call struct {
	*mock.Call
}

// HandleAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - peerID string
//   - answer webrtc.SessionDescription
func (_e *MockSignalingService_Expecter) HandleAnswer(ctx interface{}, roomID interface{}, peerID interface{}, answer interface{}) *MockSignalingService_HandleAnswer_Call {
	return &MockSignalingService_HandleAnswer_Call{Call: _e.mock.On("HandleAnswer", ctx, roomID, peerID, answer)}
}

func (_c *MockSignalingService_HandleAnswer_Call) Run(run func(ctx context.Context, roomID string, peerID string, answer webrtc.SessionDescription)) *MockSignalingService_HandleAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(webrtc.SessionDescription))
	})
	return _c
}

func (_c *MockSignalingService_HandleAnswer_Call) Return(_a0 error) *MockSignalingService_HandleAnswer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSignalingService_HandleAnswer_Call) RunAndReturn(run func(context.Context, string, string, webrtc.SessionDescription) error) *MockSignalingService_HandleAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCandidate provides a mock function with given fields: ctx, roomID, peerID, candidate
func (_m *MockSignalingService) HandleCandidate(ctx context.Context, roomID string, peerID string, candidate webrtc.ICECandidateInit) error {
	ret := _m.Called(ctx, roomID, peerID, candidate)

	if len(ret) == 0 {
		panic("no return value specified for HandleCandidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, webrtc.ICECandidateInit) error); ok {
		r0 = rf(ctx, roomID, peerID, candidate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSignalingService_HandleCandidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCandidate'
type MockSignalingService_HandleCandidate_Call struct {
	*mock.Call
}

// HandleCandidate is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - peerID string
//   - candidate webrtc.ICECandidateInit
func (_e *MockSignalingService_Expecter) HandleCandidate(ctx interface{}, roomID interface{}, peerID interface{}, candidate interface{}) *MockSignalingService_HandleCandidate_Call {
	return &MockSignalingService_HandleCandidate_Call{Call: _e.mock.On("HandleCandidate", ctx, roomID, peerID, candidate)}
}

func (_c *MockSignalingService_HandleCandidate_Call) Run(run func(ctx context.Context, roomID string, peerID string, candidate webrtc.ICECandidateInit)) *MockSignalingService_HandleCandidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(webrtc.ICECandidateInit))
	})
	return _c
}

func (_c *MockSignalingService_HandleCandidate_Call) Return(_a0 error) *MockSignalingService_HandleCandidate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSignalingService_HandleCandidate_Call) RunAndReturn(run func(context.Context, string, string, webrtc.ICECandidateInit) error) *MockSignalingService_HandleCandidate_Call {
	_c.Call.Return(run)
	return _c
}

// HandleOffer provides a mock function with given fields: ctx, roomID, peerID, offer
func (_m *MockSignalingService) HandleOffer(ctx context.Context, roomID string, peerID string, offer webrtc.SessionDescription) error {
	ret := _m.Called(ctx, roomID, peerID, offer)

	if len(ret) == 0 {
		panic("no return value specified for HandleOffer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, webrtc.SessionDescription) error); ok {
		r0 = rf(ctx, roomID, peerID, offer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSignalingService_HandleOffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleOffer'
type MockSignalingService_HandleOffer_Call struct {
	*mock.Call
}

// HandleOffer is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - peerID string
//   - offer webrtc.SessionDescription
func (_e *MockSignalingService_Expecter) HandleOffer(ctx interface{}, roomID interface{}, peerID interface{}, offer interface{}) *MockSignalingService_HandleOffer_Call {
	return &MockSignalingService_HandleOffer_Call{Call: _e.mock.On("HandleOffer", ctx, roomID, peerID, offer)}
}

func (_c *MockSignalingService_HandleOffer_Call) Run(run func(ctx context.Context, roomID string, peerID string, offer webrtc.SessionDescription)) *MockSignalingService_HandleOffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(webrtc.SessionDescription))
	})
	return _c
}

func (_c *MockSignalingService_HandleOffer_Call) Return(_a0 error) *MockSignalingService_HandleOffer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSignalingService_HandleOffer_Call) RunAndReturn(run func(context.Context, string, string, webrtc.SessionDescription) error) *MockSignalingService_HandleOffer_Call {
	_c.Call.Return(run)
	return _c
}

// Join provides a mock function with given fields: ctx, roomID, peerID, out
func (_m *MockSignalingService) Join(ctx context.Context, roomID string, peerID string, out chan<- domain.SignalMessage) error {
	ret := _m.Called(ctx, roomID, peerID, out)

	if len(ret) == 0 {
		panic("no return value specified for Join")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, chan<- domain.SignalMessage) error); ok {
		r0 = rf(ctx, roomID, peerID, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSignalingService_Join_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Join'
type MockSignalingService_Join_Call struct {
	*mock.Call
}

// Join is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - peerID string
//   - out chan<- domain.SignalMessage
func (_e *MockSignalingService_Expecter) Join(ctx interface{}, roomID interface{}, peerID interface{}, out interface{}) *MockSignalingService_Join_Call {
	return &MockSignalingService_Join_Call{Call: _e.mock.On("Join", ctx, roomID, peerID, out)}
}

func (_c *MockSignalingService_Join_Call) Run(run func(ctx context.Context, roomID string, peerID string, out chan<- domain.SignalMessage)) *MockSignalingService_Join_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(chan<- domain.SignalMessage))
	})
	return _c
}

func (_c *MockSignalingService_Join_Call) Return(_a0 error) *MockSignalingService_Join_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSignalingService_Join_Call) RunAndReturn(run func(context.Context, string, string, chan<- domain.SignalMessage) error) *MockSignalingService_Join_Call {
	_c.Call.Return(run)
	return _c
}

// Leave provides a mock function with given fields: ctx, roomID, peerID
func (_m *MockSignalingService) Leave(ctx context.Context, roomID string, peerID string) error {
	ret := _m.Called(ctx, roomID, peerID)

	if len(ret) == 0 {
		panic("no return value specified for Leave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roomID, peerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSignalingService_Leave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leave'
type MockSignalingService_Leave_Call struct {
	*mock.Call
}

// Leave is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - peerID string
func (_e *MockSignalingService_Expecter) Leave(ctx interface{}, roomID interface{}, peerID interface{}) *MockSignalingService_Leave_Call {
	return &MockSignalingService_Leave_Call{Call: _e.mock.On("Leave", ctx, roomID, peerID)}
}

func (_c *MockSignalingService_Leave_Call) Run(run func(ctx context.Context, roomID string, peerID string)) *MockSignalingService_Leave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSignalingService_Leave_Call) Return(_a0 error) *MockSignalingService_Leave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSignalingService_Leave_Call) RunAndReturn(run func(context.Context, string, string) error) *MockSignalingService_Leave_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSignalingService creates a new instance of MockSignalingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSignalingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSignalingService {
	mock := &MockSignalingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
