// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksservice

import (
	context "context"

	repository "github.com/stazoloto/zync/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockRoomService is an autogenerated mock type for the RoomService type
type MockRoomService struct {
	mock.Mock
}

type MockRoomService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomService) EXPECT() *MockRoomService_Expecter {
	return &MockRoomService_Expecter{mock: &_m.Mock}
}

// GetActiveParticipants provides a mock function with given fields: ctx, roomID
func (_m *MockRoomService) GetActiveParticipants(ctx context.Context, roomID string) ([]string, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveParticipants")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomService_GetActiveParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveParticipants'
type MockRoomService_GetActiveParticipants_Call struct {
	*mock.Call
}

// GetActiveParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockRoomService_Expecter) GetActiveParticipants(ctx interface{}, roomID interface{}) *MockRoomService_GetActiveParticipants_Call {
	return &MockRoomService_GetActiveParticipants_Call{Call: _e.mock.On("GetActiveParticipants", ctx, roomID)}
}

func (_c *MockRoomService_GetActiveParticipants_Call) Run(run func(ctx context.Context, roomID string)) *MockRoomService_GetActiveParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoomService_GetActiveParticipants_Call) Return(_a0 []string, _a1 error) *MockRoomService_GetActiveParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomService_GetActiveParticipants_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockRoomService_GetActiveParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// IsParticipant provides a mock function with given fields: ctx, roomID, userID
func (_m *MockRoomService) IsParticipant(ctx context.Context, roomID string, userID string) (bool, error) {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsParticipant")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomService_IsParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsParticipant'
type MockRoomService_IsParticipant_Call struct {
	*mock.Call
}

// IsParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - userID string
func (_e *MockRoomService_Expecter) IsParticipant(ctx interface{}, roomID interface{}, userID interface{}) *MockRoomService_IsParticipant_Call {
	return &MockRoomService_IsParticipant_Call{Call: _e.mock.On("IsParticipant", ctx, roomID, userID)}
}

func (_c *MockRoomService_IsParticipant_Call) Run(run func(ctx context.Context, roomID string, userID string)) *MockRoomService_IsParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoomService_IsParticipant_Call) Return(_a0 bool, _a1 error) *MockRoomService_IsParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomService_IsParticipant_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockRoomService_IsParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// JoinRoom provides a mock function with given fields: ctx, roomID, userID
func (_m *MockRoomService) JoinRoom(ctx context.Context, roomID string, userID string) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for JoinRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomService_JoinRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinRoom'
type MockRoomService_JoinRoom_Call struct {
	*mock.Call
}

// JoinRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - userID string
func (_e *MockRoomService_Expecter) JoinRoom(ctx interface{}, roomID interface{}, userID interface{}) *MockRoomService_JoinRoom_Call {
	return &MockRoomService_JoinRoom_Call{Call: _e.mock.On("JoinRoom", ctx, roomID, userID)}
}

func (_c *MockRoomService_JoinRoom_Call) Run(run func(ctx context.Context, roomID string, userID string)) *MockRoomService_JoinRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoomService_JoinRoom_Call) Return(_a0 error) *MockRoomService_JoinRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomService_JoinRoom_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRoomService_JoinRoom_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveRoom provides a mock function with given fields: ctx, roomID, userID
func (_m *MockRoomService) LeaveRoom(ctx context.Context, roomID string, userID string) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomService_LeaveRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveRoom'
type MockRoomService_LeaveRoom_Call struct {
	*mock.Call
}

// LeaveRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - userID string
func (_e *MockRoomService_Expecter) LeaveRoom(ctx interface{}, roomID interface{}, userID interface{}) *MockRoomService_LeaveRoom_Call {
	return &MockRoomService_LeaveRoom_Call{Call: _e.mock.On("LeaveRoom", ctx, roomID, userID)}
}

func (_c *MockRoomService_LeaveRoom_Call) Run(run func(ctx context.Context, roomID string, userID string)) *MockRoomService_LeaveRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoomService_LeaveRoom_Call) Return(_a0 error) *MockRoomService_LeaveRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomService_LeaveRoom_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRoomService_LeaveRoom_Call {
	_c.Call.Return(run)
	return _c
}

// OnDisconnect provides a mock function with given fields: ctx, userID
func (_m *MockRoomService) OnDisconnect(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for OnDisconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomService_OnDisconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnDisconnect'
type MockRoomService_OnDisconnect_Call struct {
	*mock.Call
}

// OnDisconnect is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRoomService_Expecter) OnDisconnect(ctx interface{}, userID interface{}) *MockRoomService_OnDisconnect_Call {
	return &MockRoomService_OnDisconnect_Call{Call: _e.mock.On("OnDisconnect", ctx, userID)}
}

func (_c *MockRoomService_OnDisconnect_Call) Run(run func(ctx context.Context, userID string)) *MockRoomService_OnDisconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoomService_OnDisconnect_Call) Return(_a0 error) *MockRoomService_OnDisconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomService_OnDisconnect_Call) RunAndReturn(run func(context.Context, string) error) *MockRoomService_OnDisconnect_Call {
	_c.Call.Return(run)
	return _c
}

// PublishMessage provides a mock function with given fields: ctx, roomID, payload
func (_m *MockRoomService) PublishMessage(ctx context.Context, roomID string, payload []byte) error {
	ret := _m.Called(ctx, roomID, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, roomID, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomService_PublishMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMessage'
type MockRoomService_PublishMessage_Call struct {
	*mock.Call
}

// PublishMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - payload []byte
func (_e *MockRoomService_Expecter) PublishMessage(ctx interface{}, roomID interface{}, payload interface{}) *MockRoomService_PublishMessage_Call {
	return &MockRoomService_PublishMessage_Call{Call: _e.mock.On("PublishMessage", ctx, roomID, payload)}
}

func (_c *MockRoomService_PublishMessage_Call) Run(run func(ctx context.Context, roomID string, payload []byte)) *MockRoomService_PublishMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockRoomService_PublishMessage_Call) Return(_a0 error) *MockRoomService_PublishMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomService_PublishMessage_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockRoomService_PublishMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeToRoom provides a mock function with given fields: ctx, roomID
func (_m *MockRoomService) SubscribeToRoom(ctx context.Context, roomID string) (repository.ChatSubscription, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeToRoom")
	}

	var r0 repository.ChatSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.ChatSubscription, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.ChatSubscription); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ChatSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomService_SubscribeToRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeToRoom'
type MockRoomService_SubscribeToRoom_Call struct {
	*mock.Call
}

// SubscribeToRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockRoomService_Expecter) SubscribeToRoom(ctx interface{}, roomID interface{}) *MockRoomService_SubscribeToRoom_Call {
	return &MockRoomService_SubscribeToRoom_Call{Call: _e.mock.On("SubscribeToRoom", ctx, roomID)}
}

func (_c *MockRoomService_SubscribeToRoom_Call) Run(run func(ctx context.Context, roomID string)) *MockRoomService_SubscribeToRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoomService_SubscribeToRoom_Call) Return(_a0 repository.ChatSubscription, _a1 error) *MockRoomService_SubscribeToRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomService_SubscribeToRoom_Call) RunAndReturn(run func(context.Context, string) (repository.ChatSubscription, error)) *MockRoomService_SubscribeToRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomService creates a new instance of MockRoomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomService {
	mock := &MockRoomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
