// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksservice

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// EmailExists provides a mock function with given fields: ctx, email
func (_m *MockUserService) EmailExists(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for EmailExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_EmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailExists'
type MockUserService_EmailExists_Call struct {
	*mock.Call
}

// EmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) EmailExists(ctx interface{}, email interface{}) *MockUserService_EmailExists_Call {
	return &MockUserService_EmailExists_Call{Call: _e.mock.On("EmailExists", ctx, email)}
}

func (_c *MockUserService_EmailExists_Call) Run(run func(ctx context.Context, email string)) *MockUserService_EmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_EmailExists_Call) Return(_a0 bool, _a1 error) *MockUserService_EmailExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_EmailExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockUserService_EmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *MockUserService) Login(ctx context.Context, email string, password string) (string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockUserService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockUserService_Login_Call {
	return &MockUserService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockUserService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_Login_Call) Return(_a0 string, _a1 error) *MockUserService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, verifiedToken, firstName, lastName, password
func (_m *MockUserService) Register(ctx context.Context, verifiedToken string, firstName string, lastName string, password string) (string, error) {
	ret := _m.Called(ctx, verifiedToken, firstName, lastName, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (string, error)); ok {
		return rf(ctx, verifiedToken, firstName, lastName, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) string); ok {
		r0 = rf(ctx, verifiedToken, firstName, lastName, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, verifiedToken, firstName, lastName, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - verifiedToken string
//   - firstName string
//   - lastName string
//   - password string
func (_e *MockUserService_Expecter) Register(ctx interface{}, verifiedToken interface{}, firstName interface{}, lastName interface{}, password interface{}) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, verifiedToken, firstName, lastName, password)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, verifiedToken string, firstName string, lastName string, password string)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(_a0 string, _a1 error) *MockUserService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(context.Context, string, string, string, string) (string, error)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SendVerificationCode provides a mock function with given fields: ctx, email
func (_m *MockUserService) SendVerificationCode(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_SendVerificationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerificationCode'
type MockUserService_SendVerificationCode_Call struct {
	*mock.Call
}

// SendVerificationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) SendVerificationCode(ctx interface{}, email interface{}) *MockUserService_SendVerificationCode_Call {
	return &MockUserService_SendVerificationCode_Call{Call: _e.mock.On("SendVerificationCode", ctx, email)}
}

func (_c *MockUserService_SendVerificationCode_Call) Run(run func(ctx context.Context, email string)) *MockUserService_SendVerificationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_SendVerificationCode_Call) Return(_a0 error) *MockUserService_SendVerificationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_SendVerificationCode_Call) RunAndReturn(run func(context.Context, string) error) *MockUserService_SendVerificationCode_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyCode provides a mock function with given fields: ctx, email, code
func (_m *MockUserService) VerifyCode(ctx context.Context, email string, code string) (string, error) {
	ret := _m.Called(ctx, email, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_VerifyCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCode'
type MockUserService_VerifyCode_Call struct {
	*mock.Call
}

// VerifyCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
func (_e *MockUserService_Expecter) VerifyCode(ctx interface{}, email interface{}, code interface{}) *MockUserService_VerifyCode_Call {
	return &MockUserService_VerifyCode_Call{Call: _e.mock.On("VerifyCode", ctx, email, code)}
}

func (_c *MockUserService_VerifyCode_Call) Run(run func(ctx context.Context, email string, code string)) *MockUserService_VerifyCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_VerifyCode_Call) Return(_a0 string, _a1 error) *MockUserService_VerifyCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_VerifyCode_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockUserService_VerifyCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
