// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksservice

import (
	domain "github.com/stazoloto/zync/internal/domain"
	mock "github.com/stretchr/testify/mock"

	webrtc "github.com/pion/webrtc/v3"
)

// MockMediaGateway is an autogenerated mock type for the MediaGateway type
type MockMediaGateway struct {
	mock.Mock
}

type MockMediaGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaGateway) EXPECT() *MockMediaGateway_Expecter {
	return &MockMediaGateway_Expecter{mock: &_m.Mock}
}

// HandleAnswer provides a mock function with given fields: roomID, peerID, answer
func (_m *MockMediaGateway) HandleAnswer(roomID string, peerID string, answer webrtc.SessionDescription) error {
	ret := _m.Called(roomID, peerID, answer)

	if len(ret) == 0 {
		panic("no return value specified for HandleAnswer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, webrtc.SessionDescription) error); ok {
		r0 = rf(roomID, peerID, answer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaGateway_HandleAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAnswer'
type MockMediaGateway_HandleAnswer_Call struct {
	*mock.Call
}

// HandleAnswer is a helper method to define mock.On call
//   - roomID string
//   - peerID string
//   - answer webrtc.SessionDescription
func (_e *MockMediaGateway_Expecter) HandleAnswer(roomID interface{}, peerID interface{}, answer interface{}) *MockMediaGateway_HandleAnswer_Call {
	return &MockMediaGateway_HandleAnswer_Call{Call: _e.mock.On("HandleAnswer", roomID, peerID, answer)}
}

func (_c *MockMediaGateway_HandleAnswer_Call) Run(run func(roomID string, peerID string, answer webrtc.SessionDescription)) *MockMediaGateway_HandleAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(webrtc.SessionDescription))
	})
	return _c
}

func (_c *MockMediaGateway_HandleAnswer_Call) Return(_a0 error) *MockMediaGateway_HandleAnswer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaGateway_HandleAnswer_Call) RunAndReturn(run func(string, string, webrtc.SessionDescription) error) *MockMediaGateway_HandleAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCandidate provides a mock function with given fields: roomID, peerID, candidate
func (_m *MockMediaGateway) HandleCandidate(roomID string, peerID string, candidate webrtc.ICECandidateInit) error {
	ret := _m.Called(roomID, peerID, candidate)

	if len(ret) == 0 {
		panic("no return value specified for HandleCandidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, webrtc.ICECandidateInit) error); ok {
		r0 = rf(roomID, peerID, candidate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaGateway_HandleCandidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCandidate'
type MockMediaGateway_HandleCandidate_Call struct {
	*mock.Call
}

// HandleCandidate is a helper method to define mock.On call
//   - roomID string
//   - peerID string
//   - candidate webrtc.ICECandidateInit
func (_e *MockMediaGateway_Expecter) HandleCandidate(roomID interface{}, peerID interface{}, candidate interface{}) *MockMediaGateway_HandleCandidate_Call {
	return &MockMediaGateway_HandleCandidate_Call{Call: _e.mock.On("HandleCandidate", roomID, peerID, candidate)}
}

func (_c *MockMediaGateway_HandleCandidate_Call) Run(run func(roomID string, peerID string, candidate webrtc.ICECandidateInit)) *MockMediaGateway_HandleCandidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(webrtc.ICECandidateInit))
	})
	return _c
}

func (_c *MockMediaGateway_HandleCandidate_Call) Return(_a0 error) *MockMediaGateway_HandleCandidate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaGateway_HandleCandidate_Call) RunAndReturn(run func(string, string, webrtc.ICECandidateInit) error) *MockMediaGateway_HandleCandidate_Call {
	_c.Call.Return(run)
	return _c
}

// HandleOffer provides a mock function with given fields: roomID, peerID, offer
func (_m *MockMediaGateway) HandleOffer(roomID string, peerID string, offer webrtc.SessionDescription) error {
	ret := _m.Called(roomID, peerID, offer)

	if len(ret) == 0 {
		panic("no return value specified for HandleOffer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, webrtc.SessionDescription) error); ok {
		r0 = rf(roomID, peerID, offer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaGateway_HandleOffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleOffer'
type MockMediaGateway_HandleOffer_Call struct {
	*mock.Call
}

// HandleOffer is a helper method to define mock.On call
//   - roomID string
//   - peerID string
//   - offer webrtc.SessionDescription
func (_e *MockMediaGateway_Expecter) HandleOffer(roomID interface{}, peerID interface{}, offer interface{}) *MockMediaGateway_HandleOffer_Call {
	return &MockMediaGateway_HandleOffer_Call{Call: _e.mock.On("HandleOffer", roomID, peerID, offer)}
}

func (_c *MockMediaGateway_HandleOffer_Call) Run(run func(roomID string, peerID string, offer webrtc.SessionDescription)) *MockMediaGateway_HandleOffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(webrtc.SessionDescription))
	})
	return _c
}

func (_c *MockMediaGateway_HandleOffer_Call) Return(_a0 error) *MockMediaGateway_HandleOffer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaGateway_HandleOffer_Call) RunAndReturn(run func(string, string, webrtc.SessionDescription) error) *MockMediaGateway_HandleOffer_Call {
	_c.Call.Return(run)
	return _c
}

// Join provides a mock function with given fields: roomID, peerID, out
func (_m *MockMediaGateway) Join(roomID string, peerID string, out chan<- domain.SignalMessage) error {
	ret := _m.Called(roomID, peerID, out)

	if len(ret) == 0 {
		panic("no return value specified for Join")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, chan<- domain.SignalMessage) error); ok {
		r0 = rf(roomID, peerID, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaGateway_Join_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Join'
type MockMediaGateway_Join_Call struct {
	*mock.Call
}

// Join is a helper method to define mock.On call
//   - roomID string
//   - peerID string
//   - out chan<- domain.SignalMessage
func (_e *MockMediaGateway_Expecter) Join(roomID interface{}, peerID interface{}, out interface{}) *MockMediaGateway_Join_Call {
	return &MockMediaGateway_Join_Call{Call: _e.mock.On("Join", roomID, peerID, out)}
}

func (_c *MockMediaGateway_Join_Call) Run(run func(roomID string, peerID string, out chan<- domain.SignalMessage)) *MockMediaGateway_Join_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(chan<- domain.SignalMessage))
	})
	return _c
}

func (_c *MockMediaGateway_Join_Call) Return(_a0 error) *MockMediaGateway_Join_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaGateway_Join_Call) RunAndReturn(run func(string, string, chan<- domain.SignalMessage) error) *MockMediaGateway_Join_Call {
	_c.Call.Return(run)
	return _c
}

// Leave provides a mock function with given fields: roomID, peerID
func (_m *MockMediaGateway) Leave(roomID string, peerID string) error {
	ret := _m.Called(roomID, peerID)

	if len(ret) == 0 {
		panic("no return value specified for Leave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(roomID, peerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaGateway_Leave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leave'
type MockMediaGateway_Leave_Call struct {
	*mock.Call
}

// Leave is a helper method to define mock.On call
//   - roomID string
//   - peerID string
func (_e *MockMediaGateway_Expecter) Leave(roomID interface{}, peerID interface{}) *MockMediaGateway_Leave_Call {
	return &MockMediaGateway_Leave_Call{Call: _e.mock.On("Leave", roomID, peerID)}
}

func (_c *MockMediaGateway_Leave_Call) Run(run func(roomID string, peerID string)) *MockMediaGateway_Leave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockMediaGateway_Leave_Call) Return(_a0 error) *MockMediaGateway_Leave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaGateway_Leave_Call) RunAndReturn(run func(string, string) error) *MockMediaGateway_Leave_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaGateway creates a new instance of MockMediaGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaGateway {
	mock := &MockMediaGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
