// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrepo

import mock "github.com/stretchr/testify/mock"

// MockParticipantRepository is an autogenerated mock type for the ParticipantRepository type
type MockParticipantRepository struct {
	mock.Mock
}

type MockParticipantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParticipantRepository) EXPECT() *MockParticipantRepository_Expecter {
	return &MockParticipantRepository_Expecter{mock: &_m.Mock}
}

// GetActiveParticipants provides a mock function with given fields: roomID
func (_m *MockParticipantRepository) GetActiveParticipants(roomID string) ([]string, error) {
	ret := _m.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveParticipants")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(roomID)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParticipantRepository_GetActiveParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveParticipants'
type MockParticipantRepository_GetActiveParticipants_Call struct {
	*mock.Call
}

// GetActiveParticipants is a helper method to define mock.On call
//   - roomID string
func (_e *MockParticipantRepository_Expecter) GetActiveParticipants(roomID interface{}) *MockParticipantRepository_GetActiveParticipants_Call {
	return &MockParticipantRepository_GetActiveParticipants_Call{Call: _e.mock.On("GetActiveParticipants", roomID)}
}

func (_c *MockParticipantRepository_GetActiveParticipants_Call) Run(run func(roomID string)) *MockParticipantRepository_GetActiveParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockParticipantRepository_GetActiveParticipants_Call) Return(_a0 []string, _a1 error) *MockParticipantRepository_GetActiveParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParticipantRepository_GetActiveParticipants_Call) RunAndReturn(run func(string) ([]string, error)) *MockParticipantRepository_GetActiveParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// HasActiveParticipants provides a mock function with given fields: roomID
func (_m *MockParticipantRepository) HasActiveParticipants(roomID string) (bool, error) {
	ret := _m.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveParticipants")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(roomID)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(roomID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParticipantRepository_HasActiveParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasActiveParticipants'
type MockParticipantRepository_HasActiveParticipants_Call struct {
	*mock.Call
}

// HasActiveParticipants is a helper method to define mock.On call
//   - roomID string
func (_e *MockParticipantRepository_Expecter) HasActiveParticipants(roomID interface{}) *MockParticipantRepository_HasActiveParticipants_Call {
	return &MockParticipantRepository_HasActiveParticipants_Call{Call: _e.mock.On("HasActiveParticipants", roomID)}
}

func (_c *MockParticipantRepository_HasActiveParticipants_Call) Run(run func(roomID string)) *MockParticipantRepository_HasActiveParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockParticipantRepository_HasActiveParticipants_Call) Return(_a0 bool, _a1 error) *MockParticipantRepository_HasActiveParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParticipantRepository_HasActiveParticipants_Call) RunAndReturn(run func(string) (bool, error)) *MockParticipantRepository_HasActiveParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// JoinRoom provides a mock function with given fields: roomID, userID
func (_m *MockParticipantRepository) JoinRoom(roomID string, userID string) error {
	ret := _m.Called(roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for JoinRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockParticipantRepository_JoinRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinRoom'
type MockParticipantRepository_JoinRoom_Call struct {
	*mock.Call
}

// JoinRoom is a helper method to define mock.On call
//   - roomID string
//   - userID string
func (_e *MockParticipantRepository_Expecter) JoinRoom(roomID interface{}, userID interface{}) *MockParticipantRepository_JoinRoom_Call {
	return &MockParticipantRepository_JoinRoom_Call{Call: _e.mock.On("JoinRoom", roomID, userID)}
}

func (_c *MockParticipantRepository_JoinRoom_Call) Run(run func(roomID string, userID string)) *MockParticipantRepository_JoinRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockParticipantRepository_JoinRoom_Call) Return(_a0 error) *MockParticipantRepository_JoinRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockParticipantRepository_JoinRoom_Call) RunAndReturn(run func(string, string) error) *MockParticipantRepository_JoinRoom_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveRoom provides a mock function with given fields: roomID, userID
func (_m *MockParticipantRepository) LeaveRoom(roomID string, userID string) error {
	ret := _m.Called(roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockParticipantRepository_LeaveRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveRoom'
type MockParticipantRepository_LeaveRoom_Call struct {
	*mock.Call
}

// LeaveRoom is a helper method to define mock.On call
//   - roomID string
//   - userID string
func (_e *MockParticipantRepository_Expecter) LeaveRoom(roomID interface{}, userID interface{}) *MockParticipantRepository_LeaveRoom_Call {
	return &MockParticipantRepository_LeaveRoom_Call{Call: _e.mock.On("LeaveRoom", roomID, userID)}
}

func (_c *MockParticipantRepository_LeaveRoom_Call) Run(run func(roomID string, userID string)) *MockParticipantRepository_LeaveRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockParticipantRepository_LeaveRoom_Call) Return(_a0 error) *MockParticipantRepository_LeaveRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockParticipantRepository_LeaveRoom_Call) RunAndReturn(run func(string, string) error) *MockParticipantRepository_LeaveRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParticipantRepository creates a new instance of MockParticipantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantRepository {
	mock := &MockParticipantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
