// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrepo

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPresenceRepository is an autogenerated mock type for the PresenceRepository type
type MockPresenceRepository struct {
	mock.Mock
}

type MockPresenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPresenceRepository) EXPECT() *MockPresenceRepository_Expecter {
	return &MockPresenceRepository_Expecter{mock: &_m.Mock}
}

// AddParticipant provides a mock function with given fields: ctx, roomID, userID
func (_m *MockPresenceRepository) AddParticipant(ctx context.Context, roomID string, userID string) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPresenceRepository_AddParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipant'
type MockPresenceRepository_AddParticipant_Call struct {
	*mock.Call
}

// AddParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - userID string
func (_e *MockPresenceRepository_Expecter) AddParticipant(ctx interface{}, roomID interface{}, userID interface{}) *MockPresenceRepository_AddParticipant_Call {
	return &MockPresenceRepository_AddParticipant_Call{Call: _e.mock.On("AddParticipant", ctx, roomID, userID)}
}

func (_c *MockPresenceRepository_AddParticipant_Call) Run(run func(ctx context.Context, roomID string, userID string)) *MockPresenceRepository_AddParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPresenceRepository_AddParticipant_Call) Return(_a0 error) *MockPresenceRepository_AddParticipant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPresenceRepository_AddParticipant_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPresenceRepository_AddParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveParticipantRooms provides a mock function with given fields: ctx, userID
func (_m *MockPresenceRepository) GetActiveParticipantRooms(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveParticipantRooms")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPresenceRepository_GetActiveParticipantRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveParticipantRooms'
type MockPresenceRepository_GetActiveParticipantRooms_Call struct {
	*mock.Call
}

// GetActiveParticipantRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPresenceRepository_Expecter) GetActiveParticipantRooms(ctx interface{}, userID interface{}) *MockPresenceRepository_GetActiveParticipantRooms_Call {
	return &MockPresenceRepository_GetActiveParticipantRooms_Call{Call: _e.mock.On("GetActiveParticipantRooms", ctx, userID)}
}

func (_c *MockPresenceRepository_GetActiveParticipantRooms_Call) Run(run func(ctx context.Context, userID string)) *MockPresenceRepository_GetActiveParticipantRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPresenceRepository_GetActiveParticipantRooms_Call) Return(_a0 []string, _a1 error) *MockPresenceRepository_GetActiveParticipantRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPresenceRepository_GetActiveParticipantRooms_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockPresenceRepository_GetActiveParticipantRooms_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveParticipants provides a mock function with given fields: ctx, roomID
func (_m *MockPresenceRepository) GetActiveParticipants(ctx context.Context, roomID string) ([]string, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveParticipants")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPresenceRepository_GetActiveParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveParticipants'
type MockPresenceRepository_GetActiveParticipants_Call struct {
	*mock.Call
}

// GetActiveParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockPresenceRepository_Expecter) GetActiveParticipants(ctx interface{}, roomID interface{}) *MockPresenceRepository_GetActiveParticipants_Call {
	return &MockPresenceRepository_GetActiveParticipants_Call{Call: _e.mock.On("GetActiveParticipants", ctx, roomID)}
}

func (_c *MockPresenceRepository_GetActiveParticipants_Call) Run(run func(ctx context.Context, roomID string)) *MockPresenceRepository_GetActiveParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPresenceRepository_GetActiveParticipants_Call) Return(_a0 []string, _a1 error) *MockPresenceRepository_GetActiveParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPresenceRepository_GetActiveParticipants_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockPresenceRepository_GetActiveParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveParticipant provides a mock function with given fields: ctx, roomID, userID
func (_m *MockPresenceRepository) RemoveParticipant(ctx context.Context, roomID string, userID string) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPresenceRepository_RemoveParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveParticipant'
type MockPresenceRepository_RemoveParticipant_Call struct {
	*mock.Call
}

// RemoveParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - userID string
func (_e *MockPresenceRepository_Expecter) RemoveParticipant(ctx interface{}, roomID interface{}, userID interface{}) *MockPresenceRepository_RemoveParticipant_Call {
	return &MockPresenceRepository_RemoveParticipant_Call{Call: _e.mock.On("RemoveParticipant", ctx, roomID, userID)}
}

func (_c *MockPresenceRepository_RemoveParticipant_Call) Run(run func(ctx context.Context, roomID string, userID string)) *MockPresenceRepository_RemoveParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPresenceRepository_RemoveParticipant_Call) Return(_a0 error) *MockPresenceRepository_RemoveParticipant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPresenceRepository_RemoveParticipant_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPresenceRepository_RemoveParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPresenceRepository creates a new instance of MockPresenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPresenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPresenceRepository {
	mock := &MockPresenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
