// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrepo

import (
	context "context"

	repository "github.com/stazoloto/zync/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockChatSubscriber is an autogenerated mock type for the ChatSubscriber type
type MockChatSubscriber struct {
	mock.Mock
}

type MockChatSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatSubscriber) EXPECT() *MockChatSubscriber_Expecter {
	return &MockChatSubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: ctx, roomID
func (_m *MockChatSubscriber) Subscribe(ctx context.Context, roomID string) (repository.ChatSubscription, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 repository.ChatSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.ChatSubscription, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.ChatSubscription); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ChatSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockChatSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockChatSubscriber_Expecter) Subscribe(ctx interface{}, roomID interface{}) *MockChatSubscriber_Subscribe_Call {
	return &MockChatSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, roomID)}
}

func (_c *MockChatSubscriber_Subscribe_Call) Run(run func(ctx context.Context, roomID string)) *MockChatSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockChatSubscriber_Subscribe_Call) Return(_a0 repository.ChatSubscription, _a1 error) *MockChatSubscriber_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatSubscriber_Subscribe_Call) RunAndReturn(run func(context.Context, string) (repository.ChatSubscription, error)) *MockChatSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatSubscriber creates a new instance of MockChatSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatSubscriber {
	mock := &MockChatSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
