// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrepo

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockChatPublisher is an autogenerated mock type for the ChatPublisher type
type MockChatPublisher struct {
	mock.Mock
}

type MockChatPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatPublisher) EXPECT() *MockChatPublisher_Expecter {
	return &MockChatPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, roomID, payload
func (_m *MockChatPublisher) Publish(ctx context.Context, roomID string, payload []byte) error {
	ret := _m.Called(ctx, roomID, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, roomID, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockChatPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - payload []byte
func (_e *MockChatPublisher_Expecter) Publish(ctx interface{}, roomID interface{}, payload interface{}) *MockChatPublisher_Publish_Call {
	return &MockChatPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, roomID, payload)}
}

func (_c *MockChatPublisher_Publish_Call) Run(run func(ctx context.Context, roomID string, payload []byte)) *MockChatPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockChatPublisher_Publish_Call) Return(_a0 error) *MockChatPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatPublisher_Publish_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockChatPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatPublisher creates a new instance of MockChatPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatPublisher {
	mock := &MockChatPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
