// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrepo

import mock "github.com/stretchr/testify/mock"

// MockChatSubscription is an autogenerated mock type for the ChatSubscription type
type MockChatSubscription struct {
	mock.Mock
}

type MockChatSubscription_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatSubscription) EXPECT() *MockChatSubscription_Expecter {
	return &MockChatSubscription_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function with no fields
func (_m *MockChatSubscription) Channel() <-chan []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 <-chan []byte
	if rf, ok := ret.Get(0).(func() <-chan []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []byte)
		}
	}

	return r0
}

// MockChatSubscription_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type MockChatSubscription_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
func (_e *MockChatSubscription_Expecter) Channel() *MockChatSubscription_Channel_Call {
	return &MockChatSubscription_Channel_Call{Call: _e.mock.On("Channel")}
}

func (_c *MockChatSubscription_Channel_Call) Run(run func()) *MockChatSubscription_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatSubscription_Channel_Call) Return(_a0 <-chan []byte) *MockChatSubscription_Channel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatSubscription_Channel_Call) RunAndReturn(run func() <-chan []byte) *MockChatSubscription_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockChatSubscription) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatSubscription_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockChatSubscription_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockChatSubscription_Expecter) Close() *MockChatSubscription_Close_Call {
	return &MockChatSubscription_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockChatSubscription_Close_Call) Run(run func()) *MockChatSubscription_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatSubscription_Close_Call) Return(_a0 error) *MockChatSubscription_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatSubscription_Close_Call) RunAndReturn(run func() error) *MockChatSubscription_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatSubscription creates a new instance of MockChatSubscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatSubscription(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatSubscription {
	mock := &MockChatSubscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
