// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrepo

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockVerifyCodeRepository is an autogenerated mock type for the VerifyCodeRepository type
type MockVerifyCodeRepository struct {
	mock.Mock
}

type MockVerifyCodeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifyCodeRepository) EXPECT() *MockVerifyCodeRepository_Expecter {
	return &MockVerifyCodeRepository_Expecter{mock: &_m.Mock}
}

// DeleteCode provides a mock function with given fields: ctx, email
func (_m *MockVerifyCodeRepository) DeleteCode(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerifyCodeRepository_DeleteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCode'
type MockVerifyCodeRepository_DeleteCode_Call struct {
	*mock.Call
}

// DeleteCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockVerifyCodeRepository_Expecter) DeleteCode(ctx interface{}, email interface{}) *MockVerifyCodeRepository_DeleteCode_Call {
	return &MockVerifyCodeRepository_DeleteCode_Call{Call: _e.mock.On("DeleteCode", ctx, email)}
}

func (_c *MockVerifyCodeRepository_DeleteCode_Call) Run(run func(ctx context.Context, email string)) *MockVerifyCodeRepository_DeleteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVerifyCodeRepository_DeleteCode_Call) Return(_a0 error) *MockVerifyCodeRepository_DeleteCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerifyCodeRepository_DeleteCode_Call) RunAndReturn(run func(context.Context, string) error) *MockVerifyCodeRepository_DeleteCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetCode provides a mock function with given fields: ctx, email
func (_m *MockVerifyCodeRepository) GetCode(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerifyCodeRepository_GetCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCode'
type MockVerifyCodeRepository_GetCode_Call struct {
	*mock.Call
}

// GetCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockVerifyCodeRepository_Expecter) GetCode(ctx interface{}, email interface{}) *MockVerifyCodeRepository_GetCode_Call {
	return &MockVerifyCodeRepository_GetCode_Call{Call: _e.mock.On("GetCode", ctx, email)}
}

func (_c *MockVerifyCodeRepository_GetCode_Call) Run(run func(ctx context.Context, email string)) *MockVerifyCodeRepository_GetCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVerifyCodeRepository_GetCode_Call) Return(_a0 string, _a1 error) *MockVerifyCodeRepository_GetCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerifyCodeRepository_GetCode_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockVerifyCodeRepository_GetCode_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCode provides a mock function with given fields: ctx, email, code, ttl
func (_m *MockVerifyCodeRepository) SaveCode(ctx context.Context, email string, code string, ttl time.Duration) error {
	ret := _m.Called(ctx, email, code, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, email, code, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerifyCodeRepository_SaveCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCode'
type MockVerifyCodeRepository_SaveCode_Call struct {
	*mock.Call
}

// SaveCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
//   - ttl time.Duration
func (_e *MockVerifyCodeRepository_Expecter) SaveCode(ctx interface{}, email interface{}, code interface{}, ttl interface{}) *MockVerifyCodeRepository_SaveCode_Call {
	return &MockVerifyCodeRepository_SaveCode_Call{Call: _e.mock.On("SaveCode", ctx, email, code, ttl)}
}

func (_c *MockVerifyCodeRepository_SaveCode_Call) Run(run func(ctx context.Context, email string, code string, ttl time.Duration)) *MockVerifyCodeRepository_SaveCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockVerifyCodeRepository_SaveCode_Call) Return(_a0 error) *MockVerifyCodeRepository_SaveCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerifyCodeRepository_SaveCode_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockVerifyCodeRepository_SaveCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifyCodeRepository creates a new instance of MockVerifyCodeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifyCodeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifyCodeRepository {
	mock := &MockVerifyCodeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
