// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrepo

import mock "github.com/stretchr/testify/mock"

// MockRoomRepository is an autogenerated mock type for the RoomRepository type
type MockRoomRepository struct {
	mock.Mock
}

type MockRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepository) EXPECT() *MockRoomRepository_Expecter {
	return &MockRoomRepository_Expecter{mock: &_m.Mock}
}

// CreateIfNotExists provides a mock function with given fields: roomID
func (_m *MockRoomRepository) CreateIfNotExists(roomID string) error {
	ret := _m.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for CreateIfNotExists")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomRepository_CreateIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIfNotExists'
type MockRoomRepository_CreateIfNotExists_Call struct {
	*mock.Call
}

// CreateIfNotExists is a helper method to define mock.On call
//   - roomID string
func (_e *MockRoomRepository_Expecter) CreateIfNotExists(roomID interface{}) *MockRoomRepository_CreateIfNotExists_Call {
	return &MockRoomRepository_CreateIfNotExists_Call{Call: _e.mock.On("CreateIfNotExists", roomID)}
}

func (_c *MockRoomRepository_CreateIfNotExists_Call) Run(run func(roomID string)) *MockRoomRepository_CreateIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRoomRepository_CreateIfNotExists_Call) Return(_a0 error) *MockRoomRepository_CreateIfNotExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomRepository_CreateIfNotExists_Call) RunAndReturn(run func(string) error) *MockRoomRepository_CreateIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with no fields
func (_m *MockRoomRepository) ListActive() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MockRoomRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
func (_e *MockRoomRepository_Expecter) ListActive() *MockRoomRepository_ListActive_Call {
	return &MockRoomRepository_ListActive_Call{Call: _e.mock.On("ListActive")}
}

func (_c *MockRoomRepository_ListActive_Call) Run(run func()) *MockRoomRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoomRepository_ListActive_Call) Return(_a0 []string, _a1 error) *MockRoomRepository_ListActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_ListActive_Call) RunAndReturn(run func() ([]string, error)) *MockRoomRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// SetInactive provides a mock function with given fields: roomID
func (_m *MockRoomRepository) SetInactive(roomID string) error {
	ret := _m.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for SetInactive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomRepository_SetInactive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInactive'
type MockRoomRepository_SetInactive_Call struct {
	*mock.Call
}

// SetInactive is a helper method to define mock.On call
//   - roomID string
func (_e *MockRoomRepository_Expecter) SetInactive(roomID interface{}) *MockRoomRepository_SetInactive_Call {
	return &MockRoomRepository_SetInactive_Call{Call: _e.mock.On("SetInactive", roomID)}
}

func (_c *MockRoomRepository_SetInactive_Call) Run(run func(roomID string)) *MockRoomRepository_SetInactive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRoomRepository_SetInactive_Call) Return(_a0 error) *MockRoomRepository_SetInactive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomRepository_SetInactive_Call) RunAndReturn(run func(string) error) *MockRoomRepository_SetInactive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomRepository creates a new instance of MockRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepository {
	mock := &MockRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
